name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: copy .env
        run: cp .env.example .env
      - name: install dependencies
        run: |
          bundle install
      - name: testing application
        run: |
          echo "running tests"
          rspec